update, fix workflow error

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -31,31 +31,31 @@ jobs:
       fail-fast: false
       matrix:
         settings:
-          - host: macos-latest
-            target: x86_64-apple-darwin
-            build: |
-              yarn build
-              strip -x $APP_NAME.*.node
-          - host: macos-latest
-            target: aarch64-apple-darwin
-            build: |
-              sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*;
-              export CC=$(xcrun -f clang);
-              export CXX=$(xcrun -f clang++);
-              SYSROOT=$(xcrun --sdk macosx --show-sdk-path);
-              export CFLAGS="-isysroot $SYSROOT -isystem $SYSROOT";
-              yarn build --target aarch64-apple-darwin
-              strip -x $APP_NAME.*.node
-          - host: ubuntu-latest
-            target: x86_64-unknown-linux-gnu
-            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
-            build: |
-              set -e &&
-              apt-get update
-              apt-get install -y ssh
-              cd $WORK_PATH &&
-              yarn build --target x86_64-unknown-linux-gnu &&
-              strip -x $APP_NAME.*.node
+#          - host: macos-latest
+#            target: x86_64-apple-darwin
+#            build: |
+#              yarn build
+#              strip -x $APP_NAME.*.node
+#          - host: macos-latest
+#            target: aarch64-apple-darwin
+#            build: |
+#              sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*;
+#              export CC=$(xcrun -f clang);
+#              export CXX=$(xcrun -f clang++);
+#              SYSROOT=$(xcrun --sdk macosx --show-sdk-path);
+#              export CFLAGS="-isysroot $SYSROOT -isystem $SYSROOT";
+#              yarn build --target aarch64-apple-darwin
+#              strip -x $APP_NAME.*.node
+#          - host: ubuntu-latest
+#            target: x86_64-unknown-linux-gnu
+#            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
+#            build: |
+#              set -e &&
+#              apt-get update
+#              apt-get install -y ssh
+#              cd $WORK_PATH &&
+#              yarn build --target x86_64-unknown-linux-gnu &&
+#              strip -x $APP_NAME.*.node
           - host: ubuntu-latest
             target: aarch64-unknown-linux-gnu
             docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
@@ -167,128 +167,88 @@ jobs:
           name: bindings-${{ matrix.settings.target }}
           path: ${{ env.WORK_PATH }}/${{ env.APP_NAME }}.*.node
           if-no-files-found: error
-  test-macOS-x64-binding:
-    name: Test bindings on ${{ matrix.settings.target }} - node@${{ matrix.node }}
-    needs:
-      - build
-    strategy:
-      fail-fast: false
-      matrix:
-        settings:
-          - host: macos-latest
-            target: x86_64-apple-darwin
-        node:
-          - '18'
-    runs-on: ${{ matrix.settings.host }}
-    steps:
-      - uses: actions/checkout@v4
-      - name: Configure npm for GitHub Packages
-        run: |
-          echo "@mystikonetwork:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
-          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> $HOME/.npmrc
-          cp $HOME/.npmrc $GITHUB_WORKSPACE/
-      - name: Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{ matrix.node }}
-          cache: yarn
-      - name: Install dependencies
-        run: yarn install
-        working-directory: ${{ env.WORK_PATH }}
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: bindings-${{ matrix.settings.target }}
-          path: ${{ env.WORK_PATH }}
-      - name: List packages
-        run: ls -R .
-        shell: bash
-        working-directory: ${{ env.WORK_PATH }}
-      - name: Test bindings
-        run: yarn test
-        working-directory: ${{ env.WORK_PATH }}
-  test-macOS-aarch64-binding:
-    name: Test bindings on ${{ matrix.settings.target }} - node@${{ matrix.node }}
-    needs:
-      - build
-    strategy:
-      fail-fast: false
-      matrix:
-        settings:
-          - host: macos-latest
-            target: aarch64-apple-darwin
-        node:
-          - '18'
-    runs-on: ${{ matrix.settings.host }}
-    steps:
-      - uses: actions/checkout@v4
-      - name: Configure npm for GitHub Packages
-        run: |
-          echo "@mystikonetwork:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
-          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> $HOME/.npmrc
-          cp $HOME/.npmrc $GITHUB_WORKSPACE/
-      - name: Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{ matrix.node }}
-          cache: yarn
-      - name: Install dependencies
-        run: yarn install
-        working-directory: ${{ env.WORK_PATH }}
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: bindings-${{ matrix.settings.target }}
-          path: ${{ env.WORK_PATH }}
-      - name: List packages
-        run: ls -R .
-        shell: bash
-        working-directory: ${{ env.WORK_PATH }}
-      - name: Test bindings
-        run: yarn test
-        working-directory: ${{ env.WORK_PATH }}
-  test-linux-x64-gnu-binding:
-    name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
-    needs:
-      - build
-    strategy:
-      fail-fast: false
-      matrix:
-        node:
-          - '18'
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Configure npm for GitHub Packages
-        run: |
-          echo "@mystikonetwork:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
-          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> $HOME/.npmrc
-          cp $HOME/.npmrc $GITHUB_WORKSPACE/
-      - name: Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{ matrix.node }}
-          cache: yarn
-      - name: Install dependencies
-        run: yarn install
-        working-directory: ${{ env.WORK_PATH }}
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: bindings-x86_64-unknown-linux-gnu
-          path: ${{ env.WORK_PATH }}
-      - name: List packages
-        run: ls -R .
-        shell: bash
-        working-directory: ${{ env.WORK_PATH }}
-      - name: Test bindings
-        run: |
-          docker run --rm \
-            -v $(pwd)/${{ env.WORK_PATH }}:/build \
-            -v ${{ github.workspace }}/.npmrc:/.npmrc \
-            -w /build \
-            node:${{ matrix.node }}-slim \
-            /bin/bash -c "yarn install && yarn test"
+#  test-macOS-binding:
+#    name: Test bindings on ${{ matrix.settings.target }} - node@${{ matrix.node }}
+#    needs:
+#      - build
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        settings:
+#          - host: macos-latest
+#            target: x86_64-apple-darwin
+#        node:
+#          - '18'
+#    runs-on: ${{ matrix.settings.host }}
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Configure npm for GitHub Packages
+#        run: |
+#          echo "@mystikonetwork:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
+#          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> $HOME/.npmrc
+#          cp $HOME/.npmrc $GITHUB_WORKSPACE/
+#      - name: Setup node
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: ${{ matrix.node }}
+#          cache: yarn
+#      - name: Install dependencies
+#        run: yarn install
+#        working-directory: ${{ env.WORK_PATH }}
+#      - name: Download artifacts
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: bindings-${{ matrix.settings.target }}
+#          path: ${{ env.WORK_PATH }}
+#      - name: List packages
+#        run: ls -R .
+#        shell: bash
+#        working-directory: ${{ env.WORK_PATH }}
+#      - name: Test bindings
+#        run: yarn test
+#        working-directory: ${{ env.WORK_PATH }}
+#  test-linux-x64-gnu-binding:
+#    name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
+#    needs:
+#      - build
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        node:
+#          - '18'
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Configure npm for GitHub Packages
+#        run: |
+#          echo "@mystikonetwork:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
+#          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> $HOME/.npmrc
+#          cp $HOME/.npmrc $GITHUB_WORKSPACE/
+#      - name: Setup node
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: ${{ matrix.node }}
+#          cache: yarn
+#      - name: Install dependencies
+#        run: yarn install
+#        working-directory: ${{ env.WORK_PATH }}
+#      - name: Download artifacts
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: bindings-x86_64-unknown-linux-gnu
+#          path: ${{ env.WORK_PATH }}
+#      - name: List packages
+#        run: ls -R .
+#        shell: bash
+#        working-directory: ${{ env.WORK_PATH }}
+#      - name: Test bindings
+#        run: |
+#          docker run --rm \
+#            -v $(pwd)/${{ env.WORK_PATH }}:/build \
+#            -v ${{ github.workspace }}/.npmrc:/.npmrc \
+#            -w /build \
+#            node:${{ matrix.node }}-slim \
+#            /bin/bash -c "yarn install && yarn test"
   test-linux-aarch64-gnu-binding:
     name: Test bindings on aarch64-unknown-linux-gnu - node@${{ matrix.node }}
     needs:
@@ -341,9 +301,8 @@ jobs:
     name: Publish
     runs-on: ubuntu-latest
     needs:
-      - test-macOS-x64-binding
-      - test-macOS-aarch64-binding
-      - test-linux-x64-gnu-binding
+#      - test-macOS-binding
+#      - test-linux-x64-gnu-binding
       - test-linux-aarch64-gnu-binding
     steps:
       - uses: actions/checkout@v4
