update, fix workflow error

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -3,10 +3,10 @@ env:
   DEBUG: 'napi:*'
   APP_NAME: 'mystiko-napi'
   WORK_PATH: 'napi'
+  GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
   MACOSX_DEPLOYMENT_TARGET: '10.13'
   CARGO_UNSTABLE_TARGET_APPLIES_TO_HOST: true
   CARGO_TARGET_APPLIES_TO_HOST: false
-  GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
 permissions:
   contents: write
   id-token: write
@@ -47,9 +47,21 @@ jobs:
 #              export CFLAGS="-isysroot $SYSROOT -isystem $SYSROOT";
 #              yarn build --target aarch64-apple-darwin
 #              strip -x $APP_NAME.*.node
+#          - host: ubuntu-latest
+#            target: x86_64-unknown-linux-gnu
+#            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
+#            build: |
+#              set -e
+#              apt-get update
+#              apt-get install -y ssh
+#              corepack enable
+#              corepack prepare yarn@4.0.2 --activate
+#              cd $WORK_PATH &&
+#              yarn build --target x86_64-unknown-linux-gnu &&
+#              strip -x $APP_NAME.*.node
           - host: ubuntu-latest
-            target: x86_64-unknown-linux-gnu
-            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
+            target: aarch64-unknown-linux-gnu
+            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
             build: |
               set -e
               apt-get update
@@ -57,18 +69,8 @@ jobs:
               corepack enable
               corepack prepare yarn@4.0.2 --activate
               cd $WORK_PATH &&
-              yarn build --target x86_64-unknown-linux-gnu &&
-              strip -x $APP_NAME.*.node
-#          - host: ubuntu-latest
-#            target: aarch64-unknown-linux-gnu
-#            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
-#            build: |
-#              set -e
-#              apt-get update
-#              apt-get install -y ssh
-#              cd $WORK_PATH
-#              yarn build --target aarch64-unknown-linux-gnu
-#              aarch64-unknown-linux-gnu-strip $APP_NAME.*.node
+              yarn build --target aarch64-unknown-linux-gnu &&
+              aarch64-unknown-linux-gnu-strip $APP_NAME.*.node
     name: stable - ${{ matrix.settings.target }} - node@18
     runs-on: ${{ matrix.settings.host }}
     steps:
@@ -185,11 +187,8 @@ jobs:
 #    runs-on: ${{ matrix.settings.host }}
 #    steps:
 #      - uses: actions/checkout@v4
-#      - name: Configure npm for GitHub Packages
-#        run: |
-#          echo "@mystikonetwork:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
-#          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> $HOME/.npmrc
-#          cp $HOME/.npmrc $GITHUB_WORKSPACE/
+#      - name: Enable Corepack
+#        run: corepack enable
 #      - name: Setup node
 #        uses: actions/setup-node@v4
 #        with:
@@ -210,8 +209,46 @@ jobs:
 #      - name: Test bindings
 #        run: yarn test
 #        working-directory: ${{ env.WORK_PATH }}
-  test-linux-x64-gnu-binding:
-    name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
+#  test-linux-x64-gnu-binding:
+#    name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
+#    needs:
+#      - build
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        node:
+#          - '18'
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Enable Corepack
+#        run: corepack enable
+#      - name: Setup node
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: ${{ matrix.node }}
+#          cache: yarn
+#      - name: Install dependencies
+#        run: yarn install
+#        working-directory: ${{ env.WORK_PATH }}
+#      - name: Download artifacts
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: bindings-x86_64-unknown-linux-gnu
+#          path: ${{ env.WORK_PATH }}
+#      - name: List packages
+#        run: ls -R .
+#        shell: bash
+#        working-directory: ${{ env.WORK_PATH }}
+#      - name: Test bindings
+#        run: |
+#          docker run --rm \
+#            -v ${{ github.workspace }}:/build \
+#            -w /build/${{ env.WORK_PATH }} \
+#            node:${{ matrix.node }}-slim \
+#            /bin/bash -c "yarn test"
+  test-linux-aarch64-gnu-binding:
+    name: Test bindings on aarch64-unknown-linux-gnu - node@${{ matrix.node }}
     needs:
       - build
     strategy:
@@ -224,85 +261,45 @@ jobs:
       - uses: actions/checkout@v4
       - name: Enable Corepack
         run: corepack enable
-      - name: Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{ matrix.node }}
-          cache: yarn
-      - name: Install dependencies
-        run: yarn install
-        working-directory: ${{ env.WORK_PATH }}
       - name: Download artifacts
         uses: actions/download-artifact@v3
         with:
-          name: bindings-x86_64-unknown-linux-gnu
+          name: bindings-aarch64-unknown-linux-gnu
           path: ${{ env.WORK_PATH }}
       - name: List packages
         run: ls -R .
         shell: bash
         working-directory: ${{ env.WORK_PATH }}
-      - name: Test bindings
+      - name: Enable Corepack
+        run: corepack enable
+      - name: Install dependencies
         run: |
-          docker run --rm \
-            -v ${{ github.workspace }}:/build \
-            -w /build/${{ env.WORK_PATH }} \
-            node:${{ matrix.node }}-slim \
-            /bin/bash -c "yarn test"
-#  test-linux-aarch64-gnu-binding:
-#    name: Test bindings on aarch64-unknown-linux-gnu - node@${{ matrix.node }}
-#    needs:
-#      - build
-#    strategy:
-#      fail-fast: false
-#      matrix:
-#        node:
-#          - '18'
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v4
-#      - name: Configure npm for GitHub Packages
-#        run: |
-#          echo "@mystikonetwork:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
-#          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> $HOME/.npmrc
-#          cp $HOME/.npmrc $GITHUB_WORKSPACE/
-#      - name: Download artifacts
-#        uses: actions/download-artifact@v3
-#        with:
-#          name: bindings-aarch64-unknown-linux-gnu
-#          path: ${{ env.WORK_PATH }}
-#      - name: List packages
-#        run: ls -R .
-#        shell: bash
-#        working-directory: ${{ env.WORK_PATH }}
-#      - name: Install dependencies
-#        run: |
-#          yarn config set supportedArchitectures.cpu "arm64"
-#          yarn config set supportedArchitectures.libc "glibc"
-#          yarn install
-#        working-directory: ${{ env.WORK_PATH }}
-#      - name: Set up QEMU
-#        uses: docker/setup-qemu-action@v3
-#        with:
-#          platforms: arm64
-#      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
-#        working-directory: ${{ env.WORK_PATH }}
-#      - name: Setup and run tests
-#        uses: addnab/docker-run-action@v3
-#        with:
-#          image: node:${{ matrix.node }}-slim
-#          options: '--platform linux/arm64 -v ${{ github.workspace }}:/build  -w /build/${{ env.WORK_PATH }}'
-#          run: |
-#            set -e
-#            yarn test
-#            ls -la
+          yarn config set supportedArchitectures.cpu "arm64"
+          yarn config set supportedArchitectures.libc "glibc"
+          yarn install
+        working-directory: ${{ env.WORK_PATH }}
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+        with:
+          platforms: arm64
+      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+      - name: Setup and run tests
+        uses: addnab/docker-run-action@v3
+        with:
+          image: node:${{ matrix.node }}-slim
+          options: '--platform linux/arm64 -v ${{ github.workspace }}:/build  -w /build/${{ env.WORK_PATH }}'
+          run: |
+            set -e
+            yarn test
+            ls -la
   publish:
 #    if: startsWith(github.ref, 'refs/tags/')
     name: Publish
     runs-on: ubuntu-latest
     needs:
 #      - test-macOS-binding
-      - test-linux-x64-gnu-binding
-#      - test-linux-aarch64-gnu-binding
+#      - test-linux-x64-gnu-binding
+      - test-linux-aarch64-gnu-binding
     steps:
       - uses: actions/checkout@v4
       - name: Enable Corepack
@@ -327,8 +324,6 @@ jobs:
         shell: bash
         working-directory: ${{ env.WORK_PATH }}
       - name: Publish
-        run: npm publish --access public
-        working-directory: ${{ env.WORK_PATH }}
+        run: yarn npm publish --access public
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          NPM_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
+          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
