update, fix workflow error

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,11 +1,9 @@
-name: Build
+name: Publish
 env:
   DEBUG: napi:*
   APP_NAME: "mystiko-napi"
   WORK_PATH: "napi"
   MACOSX_DEPLOYMENT_TARGET: '10.13'
-  CARGO_UNSTABLE_TARGET_APPLIES_TO_HOST: true
-  CARGO_TARGET_APPLIES_TO_HOST: false
 permissions:
   contents: write
   id-token: write
@@ -46,26 +44,26 @@ jobs:
 #              export CFLAGS="-isysroot $SYSROOT -isystem $SYSROOT";
 #              yarn build --target aarch64-apple-darwin
 #              strip -x $APP_NAME.*.node
-#          - host: ubuntu-latest
-#            target: x86_64-unknown-linux-gnu
-#            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
-#            build: |
-#              set -e &&
-#              apt-get update
-#              apt-get install -y ssh
-#              cd $WORK_PATH &&
-#              yarn build --target x86_64-unknown-linux-gnu &&
-#              strip -x $APP_NAME.*.node
           - host: ubuntu-latest
-            target: aarch64-unknown-linux-gnu
-            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
+            target: x86_64-unknown-linux-gnu
+            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
             build: |
-              set -e
+              set -e &&
               apt-get update
               apt-get install -y ssh
-              cd $WORK_PATH
-              yarn build --target aarch64-unknown-linux-gnu
-              aarch64-unknown-linux-gnu-strip $APP_NAME.*.node
+              cd $WORK_PATH &&
+              yarn build --target x86_64-unknown-linux-gnu &&
+              strip -x $APP_NAME.*.node
+#          - host: ubuntu-latest
+#            target: aarch64-unknown-linux-gnu
+#            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
+#            build: |
+#              set -e
+#              apt-get update
+#              apt-get install -y ssh
+#              cd $WORK_PATH
+#              yarn build --target aarch64-unknown-linux-gnu
+#              aarch64-unknown-linux-gnu-strip $APP_NAME.*.node
     name: stable - ${{ matrix.settings.target }} - node@18
     runs-on: ${{ matrix.settings.host }}
     steps:
@@ -207,49 +205,8 @@ jobs:
 #      - name: Test bindings
 #        run: yarn test
 #        working-directory: ${{ env.WORK_PATH }}
-#  test-linux-x64-gnu-binding:
-#    name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
-#    needs:
-#      - build
-#    strategy:
-#      fail-fast: false
-#      matrix:
-#        node:
-#          - '18'
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v4
-#      - name: Configure npm for GitHub Packages
-#        run: |
-#          echo "@mystikonetwork:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
-#          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> $HOME/.npmrc
-#          cp $HOME/.npmrc $GITHUB_WORKSPACE/
-#      - name: Setup node
-#        uses: actions/setup-node@v4
-#        with:
-#          node-version: ${{ matrix.node }}
-#          cache: yarn
-#      - name: Install dependencies
-#        run: yarn install
-#        working-directory: ${{ env.WORK_PATH }}
-#      - name: Download artifacts
-#        uses: actions/download-artifact@v3
-#        with:
-#          name: bindings-x86_64-unknown-linux-gnu
-#          path: ${{ env.WORK_PATH }}
-#      - name: List packages
-#        run: ls -R .
-#        shell: bash
-#        working-directory: ${{ env.WORK_PATH }}
-#      - name: Test bindings
-#        run: |
-#          docker run --rm \
-#            -v ${{ github.workspace }}:/build
-#            -w /build/${{ env.WORK_PATH }} \
-#            node:${{ matrix.node }}-slim \
-#            /bin/bash -c "yarn test"
-  test-linux-aarch64-gnu-binding:
-    name: Test bindings on aarch64-unknown-linux-gnu - node@${{ matrix.node }}
+  test-linux-x64-gnu-binding:
+    name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
     needs:
       - build
     strategy:
@@ -265,43 +222,85 @@ jobs:
           echo "@mystikonetwork:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
           echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> $HOME/.npmrc
           cp $HOME/.npmrc $GITHUB_WORKSPACE/
+      - name: Setup node
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ matrix.node }}
+          cache: yarn
+      - name: Install dependencies
+        run: yarn install
+        working-directory: ${{ env.WORK_PATH }}
       - name: Download artifacts
         uses: actions/download-artifact@v3
         with:
-          name: bindings-aarch64-unknown-linux-gnu
+          name: bindings-x86_64-unknown-linux-gnu
           path: ${{ env.WORK_PATH }}
       - name: List packages
         run: ls -R .
         shell: bash
         working-directory: ${{ env.WORK_PATH }}
-      - name: Install dependencies
+      - name: Test bindings
         run: |
-          yarn config set supportedArchitectures.cpu "arm64"
-          yarn config set supportedArchitectures.libc "glibc"
-          yarn install
-        working-directory: ${{ env.WORK_PATH }}
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-        with:
-          platforms: arm64
-      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
-        working-directory: ${{ env.WORK_PATH }}
-      - name: Setup and run tests
-        uses: addnab/docker-run-action@v3
-        with:
-          image: node:${{ matrix.node }}-slim
-          options: '--platform linux/arm64 -v ${{ github.workspace }}:/build  -w /build/${{ env.WORK_PATH }}'
-          run: |
-            set -e
-            yarn test
-            ls -la
+          docker run --rm \
+            -v ${{ github.workspace }}:/build
+            -w /build/${{ env.WORK_PATH }} \
+            node:${{ matrix.node }}-slim \
+            /bin/bash -c "yarn test"
+#  test-linux-aarch64-gnu-binding:
+#    name: Test bindings on aarch64-unknown-linux-gnu - node@${{ matrix.node }}
+#    needs:
+#      - build
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        node:
+#          - '18'
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Configure npm for GitHub Packages
+#        run: |
+#          echo "@mystikonetwork:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
+#          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> $HOME/.npmrc
+#          cp $HOME/.npmrc $GITHUB_WORKSPACE/
+#      - name: Download artifacts
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: bindings-aarch64-unknown-linux-gnu
+#          path: ${{ env.WORK_PATH }}
+#      - name: List packages
+#        run: ls -R .
+#        shell: bash
+#        working-directory: ${{ env.WORK_PATH }}
+#      - name: Install dependencies
+#        run: |
+#          yarn config set supportedArchitectures.cpu "arm64"
+#          yarn config set supportedArchitectures.libc "glibc"
+#          yarn install
+#        working-directory: ${{ env.WORK_PATH }}
+#      - name: Set up QEMU
+#        uses: docker/setup-qemu-action@v3
+#        with:
+#          platforms: arm64
+#      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+#        working-directory: ${{ env.WORK_PATH }}
+#      - name: Setup and run tests
+#        uses: addnab/docker-run-action@v3
+#        with:
+#          image: node:${{ matrix.node }}-slim
+#          options: '--platform linux/arm64 -v ${{ github.workspace }}:/build  -w /build/${{ env.WORK_PATH }}'
+#          run: |
+#            set -e
+#            yarn test
+#            ls -la
   publish:
+#    if: startsWith(github.ref, 'refs/tags/')
     name: Publish
     runs-on: ubuntu-latest
     needs:
 #      - test-macOS-binding
-#      - test-linux-x64-gnu-binding
-      - test-linux-aarch64-gnu-binding
+      - test-linux-x64-gnu-binding
+#      - test-linux-aarch64-gnu-binding
     steps:
       - uses: actions/checkout@v4
       - name: Configure npm for GitHub Packages
@@ -329,14 +328,7 @@ jobs:
         shell: bash
         working-directory: ${{ env.WORK_PATH }}
       - name: Publish
-        run: |
-          if git log -1 --pretty=%B | grep -q "^[0-9]+\.[0-9]+\.[0-9]+$"; then
-            npm publish --access public
-          elif git log -1 --pretty=%B | grep -q "^[0-9]+\.[0-9]+\.[0-9]+"; then
-            npm publish --tag next --access public
-          else
-            echo "Not a release, skipping publish"
-          fi
+        run: npm publish --access public
         working-directory: ${{ env.WORK_PATH }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
