update, publish workflow Install cross

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -30,8 +30,8 @@ jobs:
         targets:
           [
             'x86_64-apple-darwin',
-            'aarch64-apple-darwin',
-            'x86_64-unknown-linux-gnu',
+#            'aarch64-apple-darwin',
+#            'x86_64-unknown-linux-gnu',
             'aarch64-unknown-linux-gnu',
           ]
     name: stable - ${{ matrix.targets }} - node@18
@@ -75,160 +75,160 @@ jobs:
           name: bindings-${{ matrix.targets }}
           path: ${{ env.WORK_PATH }}/${{ env.APP_NAME }}.*.node
           if-no-files-found: error
-  test-macOS-binding:
-    name: Test bindings on ${{ matrix.settings.target }} - node@${{ matrix.node }}
-    needs:
-      - build
-    strategy:
-      fail-fast: false
-      matrix:
-        settings:
-          - host: macos-latest
-            target: x86_64-apple-darwin
-        node:
-          - '18'
-          - '20'
-    runs-on: ${{ matrix.settings.host }}
-    steps:
-      - uses: actions/checkout@v4
-      - name: Enable Corepack
-        run: corepack enable
-      - name: Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{ matrix.node }}
-          cache: yarn
-      - name: Install dependencies
-        run: yarn install
-        working-directory: ${{ env.WORK_PATH }}
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: bindings-${{ matrix.settings.target }}
-          path: ${{ env.WORK_PATH }}
-      - name: Test bindings
-        run: yarn test
-        working-directory: ${{ env.WORK_PATH }}
-  test-linux-x64-gnu-binding:
-    name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
-    needs:
-      - build
-    strategy:
-      fail-fast: false
-      matrix:
-        node:
-          - '18'
-          - '20'
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Enable Corepack
-        run: corepack enable
-      - name: Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{ matrix.node }}
-          cache: yarn
-      - name: Install dependencies
-        run: yarn install
-        working-directory: ${{ env.WORK_PATH }}
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: bindings-x86_64-unknown-linux-gnu
-          path: ${{ env.WORK_PATH }}
-      - name: Test bindings
-        run: |
-          docker run --rm \
-            -v ${{ github.workspace }}:/build \
-            -w /build/${{ env.WORK_PATH }} \
-            node:${{ matrix.node }}-slim \
-            /bin/bash -c "yarn test"
-  test-linux-aarch64-gnu-binding:
-    name: Test bindings on aarch64-unknown-linux-gnu - node@${{ matrix.node }}
-    needs:
-      - build
-    strategy:
-      fail-fast: false
-      matrix:
-        node:
-          - '18'
-          - '20'
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: bindings-aarch64-unknown-linux-gnu
-          path: ${{ env.WORK_PATH }}
-      - name: Enable Corepack
-        run: corepack enable
-      - name: Install dependencies
-        run: |
-          yarn config set supportedArchitectures.cpu "arm64"
-          yarn config set supportedArchitectures.libc "glibc"
-          yarn install
-        working-directory: ${{ env.WORK_PATH }}
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-        with:
-          platforms: arm64
-      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
-      - name: Setup and run tests
-        uses: addnab/docker-run-action@v3
-        with:
-          image: node:${{ matrix.node }}-slim
-          options: '--platform linux/arm64 -v ${{ github.workspace }}:/build  -w /build/${{ env.WORK_PATH }}'
-          run: |
-            set -e
-            yarn test
-  publish-napi:
-    name: Publish
-    runs-on: ubuntu-latest
-    needs:
-      - test-macOS-binding
-      - test-linux-x64-gnu-binding
-      - test-linux-aarch64-gnu-binding
-    steps:
-      - uses: actions/checkout@v4
-      - name: Enable Corepack
-        run: corepack enable
-      - name: Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18
-          cache: yarn
-      - name: Install dependencies
-        run: yarn install
-        working-directory: ${{ env.WORK_PATH }}
-      - name: Download all artifacts
-        uses: actions/download-artifact@v3
-        with:
-          path: ${{ env.WORK_PATH }}/artifacts
-      - name: Move artifacts
-        run: yarn artifacts
-        working-directory: ${{ env.WORK_PATH }}
-      - name: Configure npm for GitHub Packages
-        run: |
-          echo "@mystikonetwork:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
-          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> $HOME/.npmrc
-          cp $HOME/.npmrc $GITHUB_WORKSPACE/${{ env.WORK_PATH }}/.npmrc
-      - name: Prepublish
-        run: yarn prepublishOnly
-        working-directory: ${{ env.WORK_PATH }}
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
-      - name: Publish
-        run: yarn npm publish
-        working-directory: ${{ env.WORK_PATH }}
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
-      - name: Telegram Failure Notification
-        uses: appleboy/telegram-action@master
-        if: failure()
-        with:
-          message: ❗ Build failed for [${{ github.repository }}](https://github.com/${{ github.repository }}/actions) because of ${{ github.actor }}
-          format: markdown
-          to: ${{ secrets.TELEGRAM_CHAT_ID }}
-          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+#  test-macOS-binding:
+#    name: Test bindings on ${{ matrix.settings.target }} - node@${{ matrix.node }}
+#    needs:
+#      - build
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        settings:
+#          - host: macos-latest
+#            target: x86_64-apple-darwin
+#        node:
+#          - '18'
+#          - '20'
+#    runs-on: ${{ matrix.settings.host }}
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Enable Corepack
+#        run: corepack enable
+#      - name: Setup node
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: ${{ matrix.node }}
+#          cache: yarn
+#      - name: Install dependencies
+#        run: yarn install
+#        working-directory: ${{ env.WORK_PATH }}
+#      - name: Download artifacts
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: bindings-${{ matrix.settings.target }}
+#          path: ${{ env.WORK_PATH }}
+#      - name: Test bindings
+#        run: yarn test
+#        working-directory: ${{ env.WORK_PATH }}
+#  test-linux-x64-gnu-binding:
+#    name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
+#    needs:
+#      - build
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        node:
+#          - '18'
+#          - '20'
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Enable Corepack
+#        run: corepack enable
+#      - name: Setup node
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: ${{ matrix.node }}
+#          cache: yarn
+#      - name: Install dependencies
+#        run: yarn install
+#        working-directory: ${{ env.WORK_PATH }}
+#      - name: Download artifacts
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: bindings-x86_64-unknown-linux-gnu
+#          path: ${{ env.WORK_PATH }}
+#      - name: Test bindings
+#        run: |
+#          docker run --rm \
+#            -v ${{ github.workspace }}:/build \
+#            -w /build/${{ env.WORK_PATH }} \
+#            node:${{ matrix.node }}-slim \
+#            /bin/bash -c "yarn test"
+#  test-linux-aarch64-gnu-binding:
+#    name: Test bindings on aarch64-unknown-linux-gnu - node@${{ matrix.node }}
+#    needs:
+#      - build
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        node:
+#          - '18'
+#          - '20'
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Download artifacts
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: bindings-aarch64-unknown-linux-gnu
+#          path: ${{ env.WORK_PATH }}
+#      - name: Enable Corepack
+#        run: corepack enable
+#      - name: Install dependencies
+#        run: |
+#          yarn config set supportedArchitectures.cpu "arm64"
+#          yarn config set supportedArchitectures.libc "glibc"
+#          yarn install
+#        working-directory: ${{ env.WORK_PATH }}
+#      - name: Set up QEMU
+#        uses: docker/setup-qemu-action@v3
+#        with:
+#          platforms: arm64
+#      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+#      - name: Setup and run tests
+#        uses: addnab/docker-run-action@v3
+#        with:
+#          image: node:${{ matrix.node }}-slim
+#          options: '--platform linux/arm64 -v ${{ github.workspace }}:/build  -w /build/${{ env.WORK_PATH }}'
+#          run: |
+#            set -e
+#            yarn test
+#  publish-napi:
+#    name: Publish
+#    runs-on: ubuntu-latest
+#    needs:
+#      - test-macOS-binding
+#      - test-linux-x64-gnu-binding
+#      - test-linux-aarch64-gnu-binding
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Enable Corepack
+#        run: corepack enable
+#      - name: Setup node
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: 18
+#          cache: yarn
+#      - name: Install dependencies
+#        run: yarn install
+#        working-directory: ${{ env.WORK_PATH }}
+#      - name: Download all artifacts
+#        uses: actions/download-artifact@v3
+#        with:
+#          path: ${{ env.WORK_PATH }}/artifacts
+#      - name: Move artifacts
+#        run: yarn artifacts
+#        working-directory: ${{ env.WORK_PATH }}
+#      - name: Configure npm for GitHub Packages
+#        run: |
+#          echo "@mystikonetwork:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
+#          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> $HOME/.npmrc
+#          cp $HOME/.npmrc $GITHUB_WORKSPACE/${{ env.WORK_PATH }}/.npmrc
+#      - name: Prepublish
+#        run: yarn prepublishOnly
+#        working-directory: ${{ env.WORK_PATH }}
+#        env:
+#          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
+#      - name: Publish
+#        run: yarn npm publish
+#        working-directory: ${{ env.WORK_PATH }}
+#        env:
+#          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
+#      - name: Telegram Failure Notification
+#        uses: appleboy/telegram-action@master
+#        if: failure()
+#        with:
+#          message: ❗ Build failed for [${{ github.repository }}](https://github.com/${{ github.repository }}/actions) because of ${{ github.actor }}
+#          format: markdown
+#          to: ${{ secrets.TELEGRAM_CHAT_ID }}
+#          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
